[project]
name = "Bitcoin-Insurance-chain"
authors = []
description = ""
telemetry = true
requirements = []
cache_dir = "/home/runner/workspace/Bitcoin-Insurance-chain/./.requirements"
boot_contracts = ["pox", "costs-v2", "bns"]
[contracts.Bitcoin-Insurance-chain]
path = "contracts/Bitcoin-Insurance-chain.clar"

[repl]
costs_version = 2
parser_version = 2

[repl.analysis]
passes = ["check_checker"]

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
